# Generated by Django 5.2.8 on 2025-11-26 06:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='شماره تلفن')),
                ('license', models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=20, verbose_name='مجوز')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کابر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('donation_type', models.CharField(choices=[('cash', 'پول نقد'), ('credit_card', 'کارت بانکی'), ('crypto', 'رمز ارز'), ('bank transfer', 'کارت به کارت'), ('PayPal', 'پی پال'), ('other', 'سایر')], default='cash', max_length=50, verbose_name='شیوه پرداخت')),
                ('donation_amount', models.IntegerField(null=True, verbose_name='مقدار کمک')),
                ('donor_type', models.CharField(choices=[('Individual', 'شخص حقیقی'), ('Company', 'شرکت'), ('Organization', 'سازمان')], default='Individual', max_length=20, verbose_name='اهدا کننده')),
                ('message', models.TextField(null=True, verbose_name='توضیحات')),
                ('anonymize_donation', models.CharField(choices=[(True, 'بله'), (False, 'خیر')], default=False, verbose_name='ناشناس')),
                ('user', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کمک',
                'verbose_name_plural': 'کمک ها',
            },
        ),
    ]
