# Generated by Django 5.2.8 on 2025-11-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='value',
            new_name='donation_amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='donation',
            name='anonymize_donation',
            field=models.BooleanField(choices=[('بله', 'بله'), ('خیر', 'خیر')], null=True, verbose_name='ناشناس'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('cash', 'پول نقد'), ('credit_card', 'کارت بانکی'), ('crypto', 'رمز ارز'), ('bank transfer', 'کارت به کارت'), ('PayPal', 'پی پال'), ('other', 'سایر')], default='cash', max_length=50, verbose_name='شیوه پرداخت'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_type',
            field=models.CharField(choices=[('Individual', 'شخص حقیقی'), ('Company', 'شرکت'), ('Organization', 'سازمان')], default='Individual', max_length=20, verbose_name='اهدا کننده'),
        ),
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='license',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=20, verbose_name='مجوز'),
        ),
    ]
