# Generated by Django 5.2.8 on 2025-11-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_rename_value_donation_donation_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AlterField(
            model_name='donation',
            name='anonymize_donation',
            field=models.BooleanField(choices=[('yes', 'بله'), ('no', 'خیر')], default='no', verbose_name='ناشناس'),
        ),
    ]
